name: nova-hypervisor
version: ocata
summary: OpenStack Compute Service - KVM Hypervisor (nova)
description: |
  OpenStack Nova provides a cloud computing fabric controller,
  supporting a wide variety of compute technologies, including
  .
    libvirt (KVM, Xen, LXC and more),
    LXD
    Hyper-V
    VMware
    XenServer
    OpenStack Ironic.
  .
  This snap provides the hypervisor component of an OpenStack
  deployment, configured to use Libvirt/KVM + Open vSwitch
  installed using debian packages on the hosting server.
confinement: classic
grade: devel

apps:
  nova-compute:
    command: >
      env PYTHONPATH=$PYTHONPATH:$SNAP/lib/python2.7/site-packages
      $SNAP/usr/bin/python2 $SNAP/bin/snap-openstack nova-compute
    daemon: simple
  nova-api-metadata:
    command: >
      env PYTHONPATH=$PYTHONPATH:$SNAP/lib/python2.7/site-packages
      $SNAP/usr/bin/python2 $SNAP/bin/snap-openstack nova-api-metadata
    daemon: simple
  neutron-openvswitch-agent:
    command: >
      env PYTHONPATH=$PYTHONPATH:$SNAP/lib/python2.7/site-packages
      $SNAP/usr/bin/python2 $SNAP/bin/snap-openstack neutron-openvswitch-agent
    daemon: simple
  neutron-l3-agent:
    command: >
      env PYTHONPATH=$PYTHONPATH:$SNAP/lib/python2.7/site-packages
      $SNAP/usr/bin/python2 $SNAP/bin/snap-openstack neutron-l3-agent
    daemon: simple
  neutron-dhcp-agent:
    command: >
      env PYTHONPATH=$PYTHONPATH:$SNAP/lib/python2.7/site-packages
      $SNAP/usr/bin/python2 $SNAP/bin/snap-openstack neutron-dhcp-agent
    daemon: simple
  neutron-metadata-agent:
    command: >
      env PYTHONPATH=$PYTHONPATH:$SNAP/lib/python2.7/site-packages
      $SNAP/usr/bin/python2 $SNAP/bin/snap-openstack neutron-metadata-agent
    daemon: simple
  neutron-ovs-cleanup:
    command: >
      env PYTHONPATH=$PYTHONPATH:$SNAP/lib/python2.7/site-packages
      $SNAP/usr/bin/python2 $SNAP/bin/snap-openstack neutron-ovs-cleanup
    aliases:
      - neutron-ovs-cleanup
  neutron-netns-cleanup:
    command: >
      env PYTHONPATH=$PYTHONPATH:$SNAP/lib/python2.7/site-packages
      $SNAP/usr/bin/python2 $SNAP/bin/snap-openstack neutron-netns-cleanup
    aliases:
      - neutron-netns-cleanup
parts:
  ipset:
    source: http://ipset.netfilter.org/ipset-6.30.tar.bz2
    plugin: autotools
    build-packages:
      - libltdl-dev
      - libmnl-dev
    configflags:
      - "--with-kmod=no"
  dnsmasq:
    source: http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.76.tar.xz
    plugin: make
    build-packages:
      - libgmp-dev
      - libidn11-dev
      - libnetfilter-conntrack-dev
      - nettle-dev
    organize:
      usr/local/sbin/dnsmasq: bin/dnsmasq
    filesets:
      bin:
        - bin/dnsmasq
    stage: [$bin]
    prime: [$bin]
  openvswitch:
    source: http://openvswitch.org/releases/openvswitch-2.6.1.tar.gz
    plugin: autotools
    build-packages:
      - libnuma-dev
      - libssl-dev
      - python-all
      - python-setuptools
      - python-six
    stage-packages:
      - uuid-runtime
    filesets:
      bin:
        - bin/ovs-*ctl
        - bin/ovsdb-tool
        - bin/ovsdb-client
    stage: [$bin]
    snap: [$bin]
  nova:
    after:
      - patches
      - python
      - openvswitch
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/nova/nova-stable-ocata.tar.gz
    python-packages:
      - libvirt-python
      - pymysql
      - python-memcached
      - http://tarballs.openstack.org/neutron/neutron-stable-ocata.tar.gz
      - http://tarballs.openstack.org/nova-lxd/nova-lxd-stable-ocata.tar.gz
      - git+https://github.com/openstack/snap.openstack#egg=snap.openstack
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/ocata/upper-constraints.txt
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
      - libvirt-dev
      - libxml2-dev
      - libxslt1-dev
    stage-packages:
      - qemu-utils
    stage:
      - -usr/bin/2to3
      - -usr/bin/pydoc
      - -usr/bin/python2.7
      - -usr/lib/python2.7
    install: |
      touch $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/paste/__init__.py
      touch $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/repoze/__init__.py
      cd $SNAPCRAFT_PART_INSTALL
      export PATCH_DIR="../../patches/src"
      patch -p4 < $PATCH_DIR/neutron-ns-metadata-proxy-path.patch
      cd -
  templates:
    after: [nova]
    plugin: dump
    source: snap
  patches:
    plugin: dump
    source: patches
  config-nova:
    after: [nova]
    plugin: dump
    source: http://tarballs.openstack.org/nova/nova-stable-ocata.tar.gz
    filesets:
      etc:
        - etc/nova/*
    stage: [$etc]
    snap: [$etc]
  config-neutron:
    after: [nova]
    plugin: dump
    source: http://tarballs.openstack.org/neutron/neutron-stable-ocata.tar.gz
    organize:
      etc/*.conf: etc/neutron/
      etc/*.ini: etc/neutron/
      etc/*.json: etc/neutron/
      etc/rootwrap.d/*: etc/neutron/rootwrap.d/
    filesets:
      etc:
        - etc/neutron/*
    stage: [$etc]
    snap: [$etc]
  python:
    source: https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --enable-shared
      - --enable-unicode=ucs4
    build-packages:
      - libssl-dev
    prime:
      - -usr/include
    install:
      $SNAPCRAFT_PART_INSTALL/usr/bin/python2 -m ensurepip
